# Change these first
owner: Bowen-Imagery # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Fusion CBD
    url: https://www.fusioncbd.com
  - name: Bowen Imagery
    url: https://bowenimagery.com/
 

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.bowenimagery.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://bowenimagery.com/wp-content/uploads/bowen-imagery-white-logo.svg
  name: Bowen Imagery Status Page
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Home
      href: https://bowenimagery.com
    - title: Status
      href: https://status.bowenimagery.com
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
